//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiViet()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public int BaiVietID { get; set; }
        public string TuaBaiViet { get; set; }
        public string NoiDung { get; set; }
        public int TheLoai { get; set; }
        public string HinhDaiDien { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public int NguoiDungID { get; set; }
        public string BiDanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
