//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int CommentID { get; set; }
        public Nullable<int> BaiVietID { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayComment { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
    }
}
